from sqlalchemy import Column, Integer, String, DateTime, Date, Boolean, func
from app.core.database import Base

class ParameterEntity(Base):
    __tablename__ = "m_parameters"

    store_id = Column(String(8), primary_key=True, nullable=False)
    path_name = Column(String(100), nullable=False)
    bundle_execution = Column(String(10), nullable=False)
    bundle_Default_manageNumber = Column("bundle_Default_manageNumber", String(30), nullable=False)
    similar_title = Column(String(50), nullable=False)
    similar_category = Column(String(5), nullable=False)
    similar_genre = Column(String(5), nullable=False)
    similar_created = Column(String(5), nullable=False)
    rpp_execution = Column(String(5), nullable=True)
    limit_CPC = Column("limit_CPC", Integer, nullable=False)
    ranking_execution = Column(Boolean, nullable=False)
    ranking_template = Column(String(100), nullable=True)
    ranking_item_image = Column(Boolean, nullable=False)
    rakuten_report_execution = Column(Boolean, nullable=False)
    rakuten_report_num_items = Column(Integer, nullable=False)
    rakuten_outlier_execution = Column(Boolean, nullable=False)
    review_img_execution = Column(Boolean, nullable=False)
    review_img_in_ItemImg = Column("review_img_in_ItemImg", Boolean, nullable=False)
    review_count_RefValue_mini = Column("review_count_RefValue_mini", Integer, nullable=False)
    review_count_RefValue = Column("review_count_RefValue", Integer, nullable=False)
    review_template = Column(String(5), nullable=True)
    Default_profit_margin = Column("Default_profit_margin", String(5), nullable=False)
    Default_taxRate = Column("Default_taxRate", String(10), nullable=False)
    rakuten_daily_enabled = Column(Boolean, nullable=False)
    ranking_image_pc_width = Column(String(100), nullable=True)
    rpp_budget_alart_execution = Column(Boolean, nullable=False)
    rpp_budget_alart_threshold = Column(Integer, nullable=False)
    rpp_schedule_execution = Column(Boolean, nullable=False)
    search_ranking_execution = Column(Boolean, nullable=False)
    tax_Rounding = Column("tax_Rounding", String(5), nullable=False)

    delete_flg = Column(Boolean, nullable=True, server_default="0")
    create_datetime = Column(DateTime, server_default=func.now())
    update_datetime = Column(DateTime, server_default=func.now())